// doctor.ts — 環境診断とホストシムの自動生成
//
// iPhone アプリは SSH 非対話シェルから `~/.local/bin/tailii-host` を exec する。
// 非対話シェルでは node が PATH に乗らないため、node 絶対パスを埋めた薄いシムを
// `tailii setup` が自動生成する（従来は手書き手順だった）。
//
// あわせて `tailii doctor` として、初回セットアップで詰まりやすい前提
// （tmux / claude / codex CLI・リモートログイン・シム）を機械検査する。
// 検査は launch.ts が SSH exec に注入するのと同じ PATH（defaultInjectedPath）で行う。
// エージェント側の実行環境と同じ条件で探すことで「ターミナルでは見えるが
// SSH 経由では見えない」タイプの偽陽性を避ける。

import * as fs from "node:fs";
import * as net from "node:net";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { defaultInjectedPath } from "./launch.js";

// MARK: - ホストシム生成（テスタブル）

/** シム生成の結果。 */
export type ShimResult = "created" | "updated" | "unchanged" | "skipped-foreign";

/** 生成マーカー。これを含まない既存ファイルはユーザー管理とみなし上書きしない。 */
const SHIM_MARKER = "Tailii host launcher";

/** シムの内容を組み立てる（node 絶対パス + cli.js 絶対パス固定）。 */
export function shimContent(nodePath: string, cliPath: string): string {
  return (
    "#!/bin/sh\n" +
    `# ${SHIM_MARKER} — generated by \`tailii setup\` (safe to regenerate)\n` +
    `exec "${nodePath}" "${cliPath}" "$@"\n`
  );
}

/**
 * `<binDir>/tailii-host` シムを生成する（冪等）。
 * 既存内容が一致すれば何もしない。マーカーの無い既存ファイルは上書きしない
 * （ユーザーが自前管理しているシムを壊さないため）。
 */
export function ensureHostShim(binDir: string, nodePath: string, cliPath: string): ShimResult {
  fs.mkdirSync(binDir, { recursive: true });
  const shimPath = path.join(binDir, "tailii-host");
  const content = shimContent(nodePath, cliPath);

  let existing: string | null = null;
  try {
    existing = fs.readFileSync(shimPath, "utf8");
  } catch {
    existing = null;
  }
  if (existing === content) {
    fs.chmodSync(shimPath, 0o755);
    return "unchanged";
  }
  if (existing !== null && !existing.includes(SHIM_MARKER)) return "skipped-foreign";

  fs.writeFileSync(shimPath, content, { mode: 0o755 });
  fs.chmodSync(shimPath, 0o755);
  return existing === null ? "created" : "updated";
}

/** この実行自身の dist/cli.js 絶対パス（シムの exec 先）。 */
export function resolveOwnCliPath(): string {
  return path.join(path.dirname(fileURLToPath(import.meta.url)), "cli.js");
}

/** 既定のシム設置ディレクトリ（iOS 側 `HostControlCommand` の規約と対）。 */
export function defaultShimBinDir(): string {
  return path.join(os.homedir(), ".local/bin");
}

// MARK: - 環境検査（テスタブル）

/**
 * PATH 文字列からコマンドの実体を探す（`command -v` 相当）。見つからなければ null。
 */
export function findCommand(name: string, envPath: string): string | null {
  for (const dir of envPath.split(":")) {
    if (dir === "") continue;
    const candidate = path.join(dir, name);
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      if (fs.statSync(candidate).isFile() || fs.lstatSync(candidate).isSymbolicLink()) return candidate;
    } catch {
      // 次の PATH エントリへ。
    }
  }
  return null;
}

/** TCP ポートへ接続できるか（リモートログイン=sshd の稼働検査に使う）。 */
export function checkTcpPort(host: string, port: number, timeoutMs = 1500): Promise<boolean> {
  return new Promise((resolve) => {
    const socket = net.connect({ host, port });
    const done = (ok: boolean): void => {
      socket.destroy();
      resolve(ok);
    };
    socket.setTimeout(timeoutMs, () => done(false));
    socket.once("connect", () => done(true));
    socket.once("error", () => done(false));
  });
}

// MARK: - 診断レポート

/** 1 検査項目の結果。 */
export interface DoctorCheck {
  /** 表示名。 */
  label: string;
  ok: boolean;
  /** 必須項目か（false は情報提供のみで exit code に影響しない）。 */
  required: boolean;
  /** 詳細（見つかったパス、または直し方のヒント）。 */
  detail: string;
}

/** 全検査を実行する（副作用なし・シムは検査のみ）。 */
export async function collectDoctorChecks(envPath: string = defaultInjectedPath()): Promise<DoctorCheck[]> {
  const checks: DoctorCheck[] = [];

  const nodeMajor = Number(process.versions.node.split(".")[0]);
  checks.push({
    label: "Node.js 20+",
    ok: nodeMajor >= 20,
    required: true,
    detail: `v${process.versions.node}`,
  });

  const tmux = findCommand("tmux", envPath);
  checks.push({
    label: "tmux",
    ok: tmux !== null,
    required: true,
    detail: tmux ?? "見つかりません。`brew install tmux` 等で導入してください",
  });

  const claude = findCommand("claude", envPath);
  const codex = findCommand("codex", envPath);
  checks.push({
    label: "claude CLI",
    // どちらかのエージェント CLI があれば必須要件は満たす（claude 無しの codex 運用も許す）。
    ok: claude !== null,
    required: codex === null,
    detail: claude ?? "見つかりません。https://claude.com/claude-code から導入してください",
  });
  checks.push({
    label: "codex CLI(任意)",
    ok: codex !== null,
    required: false,
    detail: codex ?? "未導入(Codex セッションを使う場合のみ必要)",
  });

  const sshdUp = await checkTcpPort("127.0.0.1", 22);
  checks.push({
    label: "リモートログイン(sshd:22)",
    ok: sshdUp,
    required: true,
    detail: sshdUp
      ? "接続可"
      : "接続不可。システム設定 → 一般 → 共有 → リモートログイン を ON にしてください",
  });

  const shimPath = path.join(defaultShimBinDir(), "tailii-host");
  const shimOk = fs.existsSync(shimPath);
  checks.push({
    label: "ホストシム(~/.local/bin/tailii-host)",
    ok: shimOk,
    required: true,
    detail: shimOk ? shimPath : "未生成。`tailii setup` を実行すると自動生成されます",
  });

  // --- QUIC ゲートウェイ（任意機能。未整備でも SSH のみで全機能が動く） ---
  const { isQuicGatewayLoaded, quicCredentialsDir, resolveQuicGatewayBinary } = await import(
    "./quicGateway.js"
  );
  const gatewayPath = resolveQuicGatewayBinary(process.env);
  checks.push({
    label: "QUIC GW バイナリ(任意)",
    ok: gatewayPath !== null,
    required: false,
    detail: gatewayPath ?? "未検出(QUIC は使わず SSH のみで動作します)",
  });
  const credsDir = quicCredentialsDir();
  const credsOk = ["cert.pem", "key.pem", "token"].every((name) =>
    fs.existsSync(path.join(credsDir, name)),
  );
  checks.push({
    label: "QUIC 資格情報(~/.tailii/quic)",
    ok: credsOk,
    required: false,
    detail: credsOk ? credsDir : "未生成。`tailii setup` を実行すると自動生成されます",
  });
  const loaded = gatewayPath !== null ? await isQuicGatewayLoaded() : false;
  checks.push({
    label: "QUIC GW 常駐(launchd)",
    ok: loaded,
    required: false,
    detail: loaded
      ? "com.tailii.quic-gw 稼働中"
      : "未常駐。`tailii setup` を実行すると launchd に登録されます",
  });

  return checks;
}

/** 検査結果を人間向けに整形する。 */
export function formatDoctorChecks(checks: DoctorCheck[]): string {
  return checks
    .map((c) => `  ${c.ok ? "✓" : c.required ? "✗" : "-"} ${c.label} : ${c.detail}`)
    .join("\n");
}

/** `tailii doctor` エントリポイント。必須項目に ✗ があれば 1 を返す。 */
export async function runDoctorCommand(_argv: string[]): Promise<number> {
  const checks = await collectDoctorChecks();
  process.stdout.write("Tailii 環境診断:\n" + formatDoctorChecks(checks) + "\n");
  const failed = checks.filter((c) => c.required && !c.ok);
  if (failed.length > 0) {
    process.stdout.write(`必須項目 ${failed.length} 件が未充足です。上のヒントに従って解消してください。\n`);
    return 1;
  }
  process.stdout.write("問題は見つかりませんでした。\n");
  return 0;
}
